### PR TITLE
add sys/types.h

### PR DESCRIPTION
**Pull request by eider-i128**

### CODE REVIEW

**Comment by teran-mckinney** [comment]
Curious, I don't have any compilation issues under FreeBSD. On what system do you need `sys/types.h`?

**Comment by eider-i128** [comment]
Linux mateusz-arch 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux

**Comment by teran-mckinney** [comment]
Okay, I definitely want this to be able to buld on Linux. Let me know if it works!

**Comment by eider-i128** [comment]
It works just fine, thanks.

**Comment by teran-mckinney** [comment]
Glad to hear it! Thank you!

**Pull request merged**
